#!/bin/bash
# GUIA RÁPIDO: Testar TeamPulse Localmente

echo "╔════════════════════════════════════════════════╗"
echo "║  GUIA: Testar TeamPulse Localmente             ║"
echo "╚════════════════════════════════════════════════╝"
echo ""

echo "📋 PASSOS PARA TESTAR:"
echo ""
echo "1️⃣  INSTALAR DEPENDÊNCIAS"
echo "   cd backend"
echo "   pip install -r requirements.txt"
echo ""

echo "2️⃣  CONFIGURAR POSTGRESQL (Docker)"
echo "   docker run -d --name teampulse-db \\"
echo "     -e POSTGRES_DB=teampulse \\"
echo "     -e POSTGRES_USER=teampulse \\"
echo "     -e POSTGRES_PASSWORD=senha123 \\"
echo "     -p 5432:5432 \\"
echo "     postgres:15-alpine"
echo ""
echo "   # Criar schema"
echo "   psql postgresql://teampulse:senha123@localhost:5432/teampulse < ../database/schema.sql"
echo ""

echo "3️⃣  CRIAR SLACK APP"
echo "   - Ir a: https://api.slack.com/apps"
echo "   - Criar app 'TeamPulse'"
echo "   - Copiar Bot Token e Signing Secret"
echo ""

echo "4️⃣  CONFIGURAR .env"
echo "   cd backend"
echo "   cp .env.example .env"
echo "   # Editar .env com teus tokens do Slack"
echo ""

echo "5️⃣  RODAR A APLICAÇÃO"
echo "   # Terminal 1: Bot principal"
echo "   python app.py"
echo ""
echo "   # Terminal 2: Scheduler"
echo "   python scheduler.py"
echo ""

echo "6️⃣  TESTAR NO SLACK"
echo "   /teampulse test    # Envia check-in de teste"
echo "   /teampulse dashboard    # Ver dashboard"
echo ""

echo "═══════════════════════════════════════════════"
echo "💡 OU USAR DOCKER (MAIS FÁCIL):"
echo ""
echo "   docker-compose up"
echo ""
echo "   Isso inicia tudo automaticamente!"
echo "═══════════════════════════════════════════════"
